name: Demo Reset

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Start a machine
        run: |
          MACHINE_ID=$(flyctl machine list -a craftday --json | jq -r '.[0].id')
          flyctl machine start "$MACHINE_ID" -a craftday
          sleep 15
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Reset demo database
        run: |
          flyctl ssh console -a craftday -C "SEED_DATA=true bin/craftplan eval Craftplan.Release.reset"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
