name: Demo Reset

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-setup-action@master

      - name: Reset demo database
        run: |
          fly ssh console -a craftday -C "SEED_DATA=true bin/craftplan eval Craftplan.Release.reset"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
