name: Demo Reset

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Start a machine
        run: |
          flyctl machine start -a craftday --wait-timeout 60
          sleep 10
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Reset demo database
        run: |
          flyctl ssh console -a craftday -C "SEED_DATA=true bin/craftplan eval Craftplan.Release.reset"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
